# Generated by Django 5.0.3 on 2024-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='idno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='krapin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffno',
            field=models.IntegerField(),
        ),
    ]
