# Generated by Django 5.0.3 on 2024-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_motordetail_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordetail',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='motordetail',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
