# Generated by Django 5.0.3 on 2024-03-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_motordetail_email_motordetail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motordetail',
            name='password',
        ),
    ]
